# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Bear Blog Mod"
license = "MIT"
licenselink = "https://github.com/Mr-Sheep/hugo-bearblog-mod/blob/master/LICENSE"
description = "A Hugo theme based on hugo-bearblog theme, with some personal tweaks"
homepage = "https://github.com/Mr-Sheep/hugo-bearblog-mod"
tags = ["blog", "responsive", "minimal", "seo", "clean", "simple", "light", "minimalist", "mobile", "fast", "white", "minimalistic", "reading", "dark mode"]
features = ["favicon", "seo", "no stylesheets", "no javascript", "rss", "dark mode"]
min_version = "0.73.0"
# https://gohugo.io/content-management/taxonomies#default-taxonomies
# https://gohugo.io/templates/taxonomy-templates/#example-list-tags-in-a-single-page-template
# https://gohugo.io/templates/taxonomy-templates/#example-list-all-site-tags

[author]
  name = "MrSheep"
  homepage = "https://github.com/Mr-Sheep"

# If porting an existing theme
[original]
  name = "Hugo Bear Blog"
  homepage = "https://themes.gohugo.io/themes/hugo-bearblog/"
  repo = "https://github.com/janraasch/hugo-bearblog"
